apiVersion: v2
name: rsrp-api
description: R-SRP Ultra API Gateway
type: application
version: 1.0.0
appVersion: "1.0.0"

dependencies:
  - name: common
    version: "1.18.0"
    repository: "https://charts.bitnami.com/bitnami"
